### ISSUE TITLE
Error running docker compose

### ISSUE THREAD

**Issue by michael4reynolds** [PlusGenie/tbot-tradingboat#3]
Hi, I'm getting an error when I'm running docker-compose build.

Unpacking JRE ...
Error unpacking jar files. The architecture or bitness (32/64)
of the bundled JVM might not match your machine.

I'm on a MBP M2 Max with a fresh install of Sonoma 14.5

Any help is appreciated

**Comment by PlusGenie** [comment]
**Problems**


On the Apple M1 chip, Docker displays the following error message:

"Error unpacking jar files. The architecture or bitness (32/64) of the bundled JVM may not match your machine."



**Solutions**

I recommend reviewing the document titled "How to Set Up Tbot on TradingBoat Docker with an External TWS Workstation.pdf," available here at
* https://tbot.plusgenie.com/how-to-set-up-tbot-on-tradingboat-docker-with-an-external-tws-workstation/

This document offers a workaround for the issue, guiding you on how to run Tbot on your Apple M1/M2 using TWS outside of Docker, rather than IB Gateway. By running TWS outside the Docker container, you'll have a better chance of understanding the trading robot since you can interact with the TWS GUI.

In the long term, you'll likely run Tbot on cloud-based computers. In such scenarios, using Docker is optional. This information is also available in the book "Mastering Automated Trading - A Comprehensive Guide to Creating, Setting Up, and Optimizing TBOT on TradingBoat.pdf," so you won't encounter the same issue when operating in the cloud.

**Technical In-Depth Clarification**

Tbot in TradingBoat operates inside Linux containers, specifically using the amd64 Linux version of the IB Gateway. Although Interactive Brokers provides a Mac version of the IB Gateway compatible with Apple Silicon's ARM64 architecture, Tbot requires an ARM64 Linux version to run effectively on an Apple M1 chip. Therefore, the Mac version of IB Gateway is not a suitable alternative.
